### PR TITLE
chore: Update example to react-native 0.63.4

### PR DESCRIPTION
**Pull request by MSzalowski**
# Overview
That pull request updates react-native version to a newest - 0.63.4.
The main motivation was flipper released with RN 0.62.

Tested on:
* iPhone 12 mini (iOS 14.2) emulator
* iPhone XS Max (iOS 14.2) real device
* Android 10.0+, API 30, CPU/ABI x86 emulator

# Test Plan

These are only basic changes from rn upgrade tool - [source](https://react-native-community.github.io/upgrade-helper/?from=0.61.5&to=0.63.4)

To test them, only need to build an application and test the functionalities.
It would be great to check if the application works properly on a real android device, as I did not have this possibility.

### CODE REVIEW

**Comment by NathanBeesley** [comment]
I have Xcode 12.5 but it conflicts with the older version of react-native in master. My changes are a patch to get the example in master to build for iOS. I would be able to throw away my patch and use this if it was in master. Not sure what to do as I cannot currently build to work on good first issues. Ideas @mmazzarolo ?

**Comment by mmazzarolo** [comment]
Hey @NathanBeesley not sure I understand what you mean — are you saying you can't test this change because it would cause issues with your current flow? In that case, that's fine, I'm pretty sure we can wait for it (and I can try to test it this weekend if I find some free time) 👍

**Comment by mmazzarolo** [comment]
And thanks @MSzalowski for the PR :)

**Comment by NathanBeesley** [comment]
@mmazzarolo I have a patch that would currently make master build for me. It is simply a patch, wasn't sure what route you wanted to take.

1. Update React Native
2. Use my patch

I would think update react native, I saw this pr was here after I created my patch(haven't submitted a pr yet). I just wasn't sure if you wanted to move to a newer version of react or not, since there are some outstanding issues. If you find time this weekend to push this, I'll pull down and verify existing issues and see if they can be closed. I just need to be in a buildable/run-able state.

**Comment by NathanBeesley** [comment]
@mmazzarolo When I get time tomorrow I will run through the examples on both platforms and verify all is working as expected. If all works can I close this PR?

**Comment by mmazzarolo** [comment]
If it all works, sure 👍 Thanks

**Comment by bhishaksanyal** [comment]
Hi @mmazzarolo 
do you plan a new release soon? I have great hopes that this PR could make the example better 🙏🏻

**Pull request closed without merging**
